services:
    app:
        build:
            context: .docker/php
            args:
                TIMEZONE: ${TIMEZONE:-America/Sao_Paulo}
        volumes:
          - ./:/var/www/symfony:rw,delegated
          - /var/www/symfony/var
          - /var/www/symfony/vendor
        networks:
            - symfony_app
        depends_on:
          - db

    nginx:
        build:
            context: .docker/nginx
        volumes:
            - ./:/var/www/symfony:ro,delegated
            - ./public:/var/www/symfony/public:ro
        ports:
            - "80:80"
        networks:
            - symfony_app
        depends_on:
          - app
        env_file:
            - .docker/.env.nginx.local

    node:
        image: node:20-alpine
        working_dir: /var/www/symfony
        volumes:
          - ./:/var/www/symfony:rw,delegated
        command: sh -c "yarn install && yarn encore dev --watch"
        networks:
          - symfony_app

    db:
        image: mysql:8.0.33
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
            - MYSQL_DATABASE=${MYSQL_DATABASE:-mytour}
            - MYSQL_ROOT_HOST=%
        volumes:
            - ./.docker/mysql/data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - symfony_app

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.2.1
        ports:
            - "8080:80"
        environment:
            - PMA_HOST=db
        volumes:
            - ./.docker/phpmyadmin/theme/blueberry:/var/www/html/themes/blueberry
        depends_on:
          - db
        networks:
            - symfony_app

networks:
    symfony_app:
